export const currency = '$';
export const currentYear = new Date().getFullYear();
export const developedByLink = 'https://techzaa.getappui.com/';
export const developedBy = 'Xytek';
export const contactUs = 'info@xytek.ai';
export const buyLink = '';
export const basePath = '';
export const DEFAULT_PAGE_TITLE = 'Xytek | Let Ai runs the classroom';
export const colorVariants = ['primary', 'secondary', 'success', 'danger', 'warning', 'info', 'pink', 'purple', 'light', 'dark', 'link'];